:rootdir: ../../..
:sourcedir: {rootdir}/src/main/java

:toc:
== Исходные данные.

В БД (например Postgres) даны две таблицы (T1 и T2) одинаковой структуры (key int(PK), value jsonb).
Поле value имеет тип jsonb со следующей структурой {“threadA”: “boolean”, “threadB”: “boolean”, “queue”: “string[]”}

Необходимо написать приложение которое:
1. Заполнит таблицу T1 десятью записями со значением key=1..10 и value={}
2. Запустит два параллельных потока (threadA и threadB) каждый из которых будет выполнять следующую последовательность действий:
a.
Прочитает произвольную запись из таблицы T1 b.
Если в прочитанной записи значения value.threadA = true и value.threadB = true, то без изменений запишет ее в таблицу T2 и удалит из таблицы T1.
c.
Иначе добавит в массив value.queue имя потока и выставит флаг value.thread(A/B) = true в зависимости от того, какой из двух потоков работает с указанной записью.
Измененное значение запишет обратно в таблицу T1.
3. Оба потока должны завершиться как только в таблице T1 не останется ни одной записи.
4. Код программы должен сопровождаться комментариями, все шаги программы должны логироваться с указанием имени потока.

В качестве бонуса (не обязательно) можно реализовать 2 другие разновидности этой же программы:
1. Потоки threadA и threadB выполняются строго по очереди друг за другом.
2. Потоки threadA и threadB выполняют только обновление данных в таблице T1 (см. п. 2а и 2с), а перенос записи из таблицы T1 в T2 (см. п. 2b) выполняет отдельный поток threadC.

== Работа сервиса.

=== Локальный запуск.

1. Развернуть БД (есть docker-compose для postgres).
2. В application.yaml указать урл и креды к БД (пример представлен), свободный порт.
3. Таблицы накатываются посредством liquibase.



